"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Save, ShieldCheck } from "lucide-react";
import type { Action, Profile, WorkshopRecord, WorkshopStatus } from "@/lib/database.types";
import { createBrowserSupabaseClient } from "@/lib/supabase/client";

const fields = [
  ["participant_profile", "Perfil coletivo e territórios representados"], ["objective", "Objetivo da oficina"], ["methodology", "Metodologia e dinâmica usada"], ["materials_produced", "Materiais produzidos"],
  ["collective_diagnosis", "Diagnóstico coletivo construído"], ["main_conclusions", "Conclusões principais"], ["consensus_points", "Consensos"], ["disagreements_or_tensions", "Divergências, tensões ou dúvidas"],
  ["proposals", "Propostas"], ["priorities", "Prioridades"], ["agreements", "Acordos"], ["next_steps", "Próximos passos"], ["themes", "Temas marcados"], ["places_mentioned", "Lugares mencionados"], ["privacy_notes", "Observações de privacidade"]
] as const;
type Field = typeof fields[number][0];
type Form = Record<Field, string> & { workshop_date: string; participants_estimated: string; territories_represented: string; status: WorkshopStatus };
const empty: Form = { workshop_date: "", participants_estimated: "", territories_represented: "", status: "draft", ...Object.fromEntries(fields.map(([key]) => [key, ""])) } as Form;

export function WorkshopRecordForm({ actionId }: { actionId: string }) {
  const supabase = useMemo(() => createBrowserSupabaseClient(), []);
  const [action, setAction] = useState<Action | null>(null); const [record, setRecord] = useState<WorkshopRecord | null>(null); const [profile, setProfile] = useState<Profile | null>(null);
  const [form, setForm] = useState<Form>(empty); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { async function load() { if (!supabase) return setError("Configure o acesso ao Supabase."); const user = await supabase.auth.getUser(); const [a, r, p] = await Promise.all([supabase.from("actions").select("*").eq("id", actionId).single(), supabase.from("workshop_records").select("*").eq("action_id", actionId).maybeSingle(), user.data.user ? supabase.from("profiles").select("*").eq("id", user.data.user.id).maybeSingle() : Promise.resolve({ data: null })]); if (a.error || r.error) return setError(a.error?.message ?? r.error?.message ?? "Não foi possível carregar."); setAction(a.data as Action); setRecord(r.data as WorkshopRecord | null); setProfile(p.data as Profile | null); if (r.data) { const x = r.data as WorkshopRecord; setForm({ ...empty, ...Object.fromEntries(fields.map(([key]) => [key, x[key] ?? ""])), workshop_date: x.workshop_date ?? "", participants_estimated: x.participants_estimated?.toString() ?? "", territories_represented: x.territories_represented ?? "", status: x.status }); } } void load(); }, [actionId, supabase]);
  async function save(status: WorkshopStatus) { if (!supabase || !action) return; setSaving(true); setError(null); const payload = { action_id: actionId, workshop_date: form.workshop_date || null, participants_estimated: form.participants_estimated ? Number(form.participants_estimated) : null, territories_represented: form.territories_represented || null, status, ...Object.fromEntries(fields.map(([key]) => [key, form[key] || null])) }; const result = record ? await supabase.from("workshop_records").update(payload).eq("id", record.id).select().single() : await supabase.from("workshop_records").insert({ ...payload, status: "draft", created_by: (await supabase.auth.getUser()).data.user?.id ?? null }).select().single(); setSaving(false); if (result.error) return setError(result.error.message); const saved = result.data as WorkshopRecord; setRecord(saved); setForm((current) => ({ ...current, status: saved.status })); setMessage(!record && status !== "draft" ? "Registro salvo como rascunho. Envie novamente para alterar o status." : status === "approved" ? "Registro coletivo aprovado. Nenhuma publicação foi realizada automaticamente." : "Registro coletivo salvo."); }
  if (error && !action) return <p className="rounded-2xl bg-red-50 p-5 text-red-800">{error}</p>;
  if (!action) return <p>Carregando oficina...</p>;
  if (action.action_type !== "oficina") return <p className="rounded-2xl bg-amber-50 p-5 text-amber-900">Esta ação não é do tipo oficina.</p>;
  const canApprove = profile?.role === "admin" || profile?.role === "coordenacao";
  return <section className="mx-auto max-w-4xl pb-10"><Link href={`/acoes/${actionId}`} className="inline-flex items-center gap-2 text-sm font-bold text-semear-green"><ArrowLeft className="h-4 w-4" />Voltar para ação</Link><h1 className="mt-5 text-3xl font-extrabold text-semear-green">Registro coletivo de oficina</h1><p className="mt-2 text-stone-600">{action.title}. Não registre nomes, CPF, telefone, endereço ou falas individuais identificáveis.</p><div className="mt-6 grid gap-4 rounded-3xl bg-white/80 p-6 shadow-premium-sm sm:grid-cols-2"><label>Data<input type="date" value={form.workshop_date} onChange={e=>setForm({...form,workshop_date:e.target.value})} className="mt-1 w-full rounded-xl border p-3" /></label><label>Participantes estimados<input type="number" min="0" value={form.participants_estimated} onChange={e=>setForm({...form,participants_estimated:e.target.value})} className="mt-1 w-full rounded-xl border p-3" /></label><label className="sm:col-span-2">Territórios representados (coletivamente)<textarea value={form.territories_represented} onChange={e=>setForm({...form,territories_represented:e.target.value})} className="mt-1 min-h-24 w-full rounded-xl border p-3" /></label>{fields.map(([key,label])=><label key={key} className="sm:col-span-2">{label}<textarea value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 min-h-28 w-full rounded-xl border p-3" /></label>)}</div>{error && <p className="mt-4 text-red-800">{error}</p>}{message && <p className="mt-4 text-semear-green">{message}</p>}<div className="mt-5 flex flex-wrap gap-3"><button disabled={saving} onClick={()=>void save("draft")} className="inline-flex items-center gap-2 rounded-xl bg-semear-green px-5 py-3 font-bold text-white"><Save className="h-4 w-4" />Salvar rascunho</button><button disabled={saving} onClick={()=>void save("submitted")} className="rounded-xl border px-5 py-3 font-bold">Enviar para revisão</button>{canApprove && <button disabled={saving} onClick={()=>void save("approved")} className="inline-flex items-center gap-2 rounded-xl bg-stone-900 px-5 py-3 font-bold text-white"><ShieldCheck className="h-4 w-4" />Aprovar</button>}</div></section>;
}
