"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Printer } from "lucide-react";
import type { Action, Neighborhood, WorkshopRecord } from "@/lib/database.types";
import { createBrowserSupabaseClient } from "@/lib/supabase/client";

type ActionWithNeighborhood = Action & { neighborhoods: Pick<Neighborhood, "id" | "name"> | null };
const sections: Array<[keyof WorkshopRecord, string]> = [["objective","Objetivo"],["methodology","Metodologia"],["materials_produced","Materiais produzidos"],["collective_diagnosis","Diagnóstico coletivo"],["main_conclusions","Conclusões coletivas"],["consensus_points","Consensos"],["disagreements_or_tensions","Divergências, tensões ou dúvidas"],["proposals","Propostas"],["priorities","Prioridades"],["agreements","Acordos"],["next_steps","Encaminhamentos"],["themes","Leitura temática"],["places_mentioned","Lugares mencionados"]];

function useWorkshop(actionId: string) { const supabase = useMemo(()=>createBrowserSupabaseClient(),[]); const [action,setAction]=useState<ActionWithNeighborhood|null>(null); const [record,setRecord]=useState<WorkshopRecord|null>(null); const [error,setError]=useState<string|null>(null); useEffect(()=>{async function load(){if(!supabase)return setError("Configure o acesso ao Supabase.");const [a,r]=await Promise.all([supabase.from("actions").select("*, neighborhoods:neighborhood_id(id,name)").eq("id",actionId).single(),supabase.from("workshop_records").select("*").eq("action_id",actionId).maybeSingle()]);if(a.error||r.error)return setError(a.error?.message??r.error?.message??"Erro ao carregar oficina.");setAction(a.data as ActionWithNeighborhood);setRecord(r.data as WorkshopRecord|null)}void load()},[actionId,supabase]);return{action,record,error}; }
function Header({ action, record, title }: { action: ActionWithNeighborhood; record: WorkshopRecord | null; title: string }) { return <><Link href={`/acoes/${action.id}`} className="inline-flex items-center gap-2 text-sm font-bold text-semear-green"><ArrowLeft className="h-4 w-4" />Voltar para ação</Link><h1 className="mt-5 text-3xl font-extrabold text-semear-green">{title} — {action.title}</h1><p className="mt-2 text-sm text-stone-600">{record?.workshop_date ?? action.action_date} · {action.location_reference ?? "Local não informado"} · {action.neighborhoods?.name ?? "Território não informado"} · {record?.participants_estimated ?? "—"} participantes estimados · Status: {record?.status ?? "sem registro"}</p></> }
export function WorkshopDossier({ actionId }: { actionId: string }) { const {action,record,error}=useWorkshop(actionId); if(error)return <p className="text-red-800">{error}</p>;if(!action)return <p>Carregando dossiê...</p>;if(!record)return <section><Header action={action} record={null} title="Dossiê da oficina"/><p className="mt-6 rounded-2xl bg-amber-50 p-5 text-amber-900">Ainda não há registro coletivo. <Link className="font-bold underline" href={`/acoes/${actionId}/oficina`}>Registrar oficina</Link>.</p></section>;return <article className="pb-10"><Header action={action} record={record} title="Dossiê da oficina"/><div className="mt-6 grid gap-4">{sections.map(([key,label])=>record[key]?<section key={key} className="rounded-3xl bg-white/80 p-6 shadow-premium-sm"><h2 className="font-bold text-semear-green">{label}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-stone-700">{String(record[key])}</p></section>:null)}<section className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-bold text-amber-900">Limites metodológicos</h2><p className="mt-2 text-sm leading-6 text-amber-900">Esta oficina não representa estatisticamente a população. As conclusões são produção coletiva do grupo presente e não substituem escutas individuais complementares.</p></section></div></article>; }
export function WorkshopDebrief({ actionId }: { actionId: string }) { const {action,record,error}=useWorkshop(actionId); if(error)return <p className="text-red-800">{error}</p>;if(!action)return <p>Carregando devolutiva...</p>;if(!record || record.status!=="approved")return <section><Header action={action} record={record} title="Devolutiva da oficina"/><p className="mt-6 rounded-2xl bg-amber-50 p-5 text-amber-900">A devolutiva pública só pode usar uma conclusão coletiva aprovada. Nenhuma publicação é automática.</p></section>;return <article className="pb-10"><Header action={action} record={record} title="Devolutiva da oficina"/><button onClick={()=>window.print()} className="mt-5 inline-flex items-center gap-2 rounded-xl border px-4 py-2 font-bold text-semear-green"><Printer className="h-4 w-4"/>Imprimir</button><div className="mt-6 grid gap-4">{sections.filter(([key])=>!["materials_produced","places_mentioned"].includes(key)).map(([key,label])=>record[key]?<section key={key} className="rounded-3xl bg-white/80 p-6 shadow-premium-sm"><h2 className="font-bold text-semear-green">{label}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-stone-700">{String(record[key])}</p></section>:null)}<section className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-bold text-amber-900">Limites da leitura</h2><p className="mt-2 text-sm leading-6 text-amber-900">Esta devolutiva apresenta conclusões coletivas da oficina, sem expor participantes e sem afirmar que representa toda a população.</p></section></div></article>; }
